<?php
/**
 * Formal employee profile document rendered by Dompdf (EmployeesController::pdf).
 * Dompdf can't use CSS variables/flex/grid — tables and inline colours only.
 *
 * @var array $employee @var array $addresses @var array $family @var array $emergency
 * @var array $education @var array $experience @var array $documents @var ?array $banks
 * @var ?array $shift @var ?string $photoUri @var ?string $logoUri
 */
$accent     = company_accent_color() ?? '#1f6f5c';
$accentSoft = company_accent_rgba(.10);

$date = static function (?string $v): string {
    if (! $v || str_starts_with($v, '0000')) {
        return '—';
    }
    $ts = strtotime($v);

    return $ts ? date('d M Y', $ts) : esc($v);
};
$val   = static fn ($v): string => ($v === null || trim((string) $v) === '') ? '—' : esc((string) $v);
$title = static fn (?string $v): string => ($v === null || $v === '') ? '—' : esc(ucwords(str_replace('_', ' ', $v)));

$fullName = trim($employee['first_name'] . ' ' . ($employee['middle_name'] ? $employee['middle_name'] . ' ' : '') . $employee['last_name']);

$byType    = [];
foreach ($addresses as $a) {
    $byType[$a['address_type']] = $a;
}
$formatAddress = static function (array $a) use ($val): string {
    if (! $a) {
        return '—';
    }
    $parts = array_filter([
        $a['address_line1'] ?? null, $a['address_line2'] ?? null, $a['city'] ?? null, $a['district'] ?? null,
        $a['state'] ?? null, $a['country'] ?? null,
    ], static fn ($p) => $p !== null && trim((string) $p) !== '');
    $line = esc(implode(', ', $parts));
    if (! empty($a['pincode'])) {
        $line .= ' - ' . esc($a['pincode']);
    }

    return $line !== '' ? $line : '—';
};

// Renders 2 label/value pairs per row.
$pairs = static function (array $items): string {
    $html = '<table class="kv">';
    foreach (array_chunk($items, 2) as $row) {
        $html .= '<tr>';
        foreach ($row as [$label, $value]) {
            $html .= '<td class="k">' . $label . '</td><td class="v">' . $value . '</td>';
        }
        if (count($row) === 1) {
            $html .= '<td class="k"></td><td class="v"></td>';
        }
        $html .= '</tr>';
    }

    return $html . '</table>';
};
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Employee Profile - <?= esc($fullName) ?></title>
<style>
  @page { margin: 28px 34px 50px 34px; }
  body { font-family: Helvetica, Arial, sans-serif; font-size: 9.5px; color: #1A1B2E; line-height: 1.4; }
  table { width: 100%; border-collapse: collapse; }
  .head td { vertical-align: middle; }
  .company { font-size: 15px; font-weight: bold; color: <?= $accent ?>; }
  .doc-title { font-size: 9px; letter-spacing: 1.5px; text-transform: uppercase; color: #5C5F77; }
  .rule { border-top: 2.5px solid <?= $accent ?>; margin: 8px 0 12px; }

  .id-card { border: 1px solid #E0E1EC; background: <?= $accentSoft ?>; }
  .id-card td { padding: 10px 12px; vertical-align: middle; }
  .photo { width: 78px; height: 78px; border: 2px solid #fff; }
  .photo-ph { width: 78px; height: 78px; background: <?= $accent ?>; color: #fff; font-size: 28px; font-weight: bold; text-align: center; line-height: 78px; }
  .name { font-size: 17px; font-weight: bold; margin: 0 0 3px; }
  .sub { color: #5C5F77; font-size: 10px; }
  .status { display: inline-block; padding: 1px 8px; border-radius: 8px; background: <?= $accent ?>; color: #fff; font-size: 8.5px; }
  .code { font-size: 10px; text-align: right; color: #5C5F77; }
  .code b { display: block; font-size: 13px; color: #1A1B2E; }

  h2 { font-size: 10.5px; text-transform: uppercase; letter-spacing: .8px; color: <?= $accent ?>;
       border-bottom: 1px solid #E0E1EC; padding: 0 0 3px; margin: 14px 0 6px; }
  .kv td { padding: 3px 6px; border-bottom: 1px solid #F0F1F7; vertical-align: top; }
  .kv td.k { width: 17%; color: #5C5F77; }
  .kv td.v { width: 33%; font-weight: bold; }
  .grid th { background: <?= $accentSoft ?>; text-align: left; padding: 4px 6px; border: 1px solid #E0E1EC; font-size: 9px; }
  .grid td { padding: 4px 6px; border: 1px solid #E0E1EC; vertical-align: top; }
  .grid tr:nth-child(even) td { background: #FAFAFD; }
  .empty { color: #8A8DA3; font-style: italic; padding: 2px 0; }
  .nobreak { page-break-inside: avoid; }

  .footer { position: fixed; bottom: -34px; left: 0; right: 0; border-top: 1px solid #E0E1EC; padding-top: 4px; font-size: 8px; color: #8A8DA3; }
  .footer td { padding: 0; }
  .pn:after { content: counter(page); }
</style>
</head>
<body>

<div class="footer">
  <table><tr>
    <td>Confidential — for authorised HR use only<?= $generatedBy ? ' · Generated by ' . esc($generatedBy) : '' ?> · <?= esc(date('d M Y, h:i A')) ?></td>
    <td style="text-align:right">Page <span class="pn"></span></td>
  </tr></table>
</div>

<table class="head">
  <tr>
    <td style="width:60px"><?php if ($logoUri): ?><img src="<?= $logoUri ?>" style="max-height:44px; max-width:56px"><?php endif; ?></td>
    <td>
      <div class="company"><?= esc($companyName) ?></div>
      <div class="doc-title">Employee Profile</div>
    </td>
    <td style="text-align:right" class="doc-title">Employee ID<br><b style="font-size:12px;color:#1A1B2E;letter-spacing:0"><?= esc($employee['employee_code']) ?></b></td>
  </tr>
</table>
<div class="rule"></div>

<table class="id-card">
  <tr>
    <td style="width:90px">
      <?php if ($photoUri): ?>
        <img class="photo" src="<?= $photoUri ?>">
      <?php else: ?>
        <div class="photo-ph"><?= esc(strtoupper(mb_substr($employee['first_name'], 0, 1) . mb_substr($employee['last_name'], 0, 1))) ?></div>
      <?php endif; ?>
    </td>
    <td>
      <p class="name"><?= esc($fullName) ?></p>
      <div class="sub"><?= esc($employee['designation_name']) ?> · <?= esc($employee['department_name']) ?></div>
      <div class="sub" style="margin:2px 0 5px"><?= esc($employee['branch_name']) ?></div>
      <span class="status"><?= esc(employee_status_label($employee['status'])) ?></span>
    </td>
    <td class="code">Date of joining<b><?= $date($employee['date_of_joining']) ?></b></td>
  </tr>
</table>

<h2>Contact Details</h2>
<?= $pairs([
    ['Mobile', $val($employee['mobile'])],
    ['Alternate mobile', $val($employee['alternate_mobile'] ?? null)],
    ['Company email', $val($employee['company_email'] ?? null)],
    ['Personal email', $val($employee['personal_email'] ?? null)],
]) ?>

<h2>Personal Information</h2>
<?= $pairs([
    ['Gender', $title($employee['gender'] ?? null)],
    ['Date of birth', $date($employee['date_of_birth'] ?? null)],
    ['Blood group', $val($employee['blood_group'] ?? null)],
    ['Marital status', $title($employee['marital_status'] ?? null)],
    ['Nationality', $val($employee['nationality'] ?? null)],
    ['Aadhaar', $val($employee['aadhaar_number'] ?? null)],
    ['PAN', $val($employee['pan_number'] ?? null)],
    ['Passport', $val($employee['passport_number'] ?? null)],
    ['Driving licence', $val($employee['driving_license_number'] ?? null)],
]) ?>

<h2>Address</h2>
<table class="kv">
  <tr><td class="k">Permanent</td><td class="v" style="width:83%;font-weight:normal"><?= $formatAddress($byType['permanent'] ?? []) ?></td></tr>
  <tr><td class="k">Current</td><td class="v" style="width:83%;font-weight:normal"><?= $formatAddress($byType['current'] ?? []) ?></td></tr>
</table>

<h2>Employment Details</h2>
<?= $pairs([
    ['Branch', $val($employee['branch_name'])],
    ['Department', $val($employee['department_name'])],
    ['Designation', $val($employee['designation_name'])],
    ['Reporting manager', $val($employee['manager_name'] ?? null)],
    ['Employment type', $title($employee['employment_type'] ?? null)],
    ['Category', $val($employee['employment_category'] ?? null)],
    ['Work location', $val($employee['work_location'] ?? null)],
    ['Date of joining', $date($employee['date_of_joining'])],
    ['Date of confirmation', $date($employee['date_of_confirmation'] ?? null)],
    ['Probation period', ! empty($employee['probation_period_months']) ? esc($employee['probation_period_months']) . ' months' : '—'],
    ['Shift', $shift ? esc($shift['name']) . ' (' . esc(substr($shift['start_time'], 0, 5)) . ' – ' . esc(substr($shift['end_time'], 0, 5)) . ')' : '—'],
    ['Status', esc(employee_status_label($employee['status']))],
]) ?>

<?php if ($banks !== null): ?>
  <h2>Bank Details</h2>
  <?php if (! $banks): ?>
    <div class="empty">No bank accounts on file.</div>
  <?php else: ?>
    <table class="grid nobreak">
      <tr><th>Account holder</th><th>Bank / Branch</th><th>Account no.</th><th>IFSC</th><th>UPI</th><th>Primary</th></tr>
      <?php foreach ($banks as $b): ?>
        <tr>
          <td><?= $val($b['account_holder_name']) ?></td>
          <td><?= $val($b['bank_name']) ?><?= ! empty($b['branch_name']) ? '<br><span class="sub">' . esc($b['branch_name']) . '</span>' : '' ?></td>
          <td><?= esc(mask_account_number($b['account_number'])) ?></td>
          <td><?= $val($b['ifsc_code']) ?></td>
          <td><?= $val($b['upi_id'] ?? null) ?></td>
          <td><?= $b['is_primary'] ? 'Yes' : '—' ?></td>
        </tr>
      <?php endforeach; ?>
    </table>
  <?php endif; ?>
<?php endif; ?>

<h2>Family Members</h2>
<?php if (! $family): ?>
  <div class="empty">No family members on file.</div>
<?php else: ?>
  <table class="grid">
    <tr><th>Name</th><th>Relationship</th><th>Date of birth</th><th>Occupation</th><th>Dependent</th><th>Nominee</th></tr>
    <?php foreach ($family as $m): ?>
      <tr>
        <td><?= $val($m['name']) ?></td><td><?= $title($m['relationship']) ?></td><td><?= $date($m['dob'] ?? null) ?></td>
        <td><?= $val($m['occupation'] ?? null) ?></td><td><?= $m['is_dependent'] ? 'Yes' : 'No' ?></td><td><?= $m['is_nominee'] ? 'Yes' : 'No' ?></td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>

<h2>Emergency Contacts</h2>
<?php if (! $emergency): ?>
  <div class="empty">No emergency contacts on file.</div>
<?php else: ?>
  <table class="grid">
    <tr><th>Priority</th><th>Name</th><th>Relationship</th><th>Phone</th><th>Alternate phone</th></tr>
    <?php foreach ($emergency as $c): ?>
      <tr>
        <td><?= $val($c['priority']) ?></td><td><?= $val($c['name']) ?></td><td><?= $title($c['relationship']) ?></td>
        <td><?= $val($c['phone']) ?></td><td><?= $val($c['alternate_phone'] ?? null) ?></td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>

<h2>Education</h2>
<?php if (! $education): ?>
  <div class="empty">No education records on file.</div>
<?php else: ?>
  <table class="grid">
    <tr><th>Qualification</th><th>Institution</th><th>Board / University</th><th>% / CGPA</th><th>Year</th></tr>
    <?php foreach ($education as $r): ?>
      <tr>
        <td><?= $val($r['qualification']) ?></td><td><?= $val($r['institution']) ?></td><td><?= $val($r['board_university'] ?? null) ?></td>
        <td><?= $val($r['percentage_cgpa'] ?? null) ?></td><td><?= $val($r['year_of_passing'] ?? null) ?></td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>

<h2>Work Experience</h2>
<?php if (! $experience): ?>
  <div class="empty">No previous experience on file.</div>
<?php else: ?>
  <table class="grid">
    <tr><th>Company</th><th>Designation</th><th>From</th><th>To</th><th>Years</th></tr>
    <?php foreach ($experience as $r): ?>
      <tr>
        <td><?= $val($r['company_name']) ?></td><td><?= $val($r['designation'] ?? null) ?></td><td><?= $date($r['from_date']) ?></td>
        <td><?= ! empty($r['to_date']) ? $date($r['to_date']) : 'Present' ?></td><td><?= $val($r['years_experience'] ?? null) ?></td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>

<?php if ($documents): ?>
  <h2>Documents on File</h2>
  <table class="grid">
    <tr><th>Type</th><th>Number</th><th>Expiry</th><th>Status</th></tr>
    <?php foreach ($documents as $d): ?>
      <tr>
        <td><?= $title($d['document_type']) ?></td><td><?= $val($d['document_number'] ?? null) ?></td>
        <td><?= $date($d['expiry_date'] ?? null) ?></td><td><?= esc(ucfirst($d['status'])) ?></td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>

</body>
</html>
